print('-'*50)
print('   Bem-vindo ao aplicativo de reajuste salarial')
print('-'*50)
salario = round(float(input(' Qual o salário que vamos reajustar? R$ ')),2)
porcentagem = round(float(input(' Informe a porcentagem de reajuste: ')),2)
reajuste = salario * (1 + (porcentagem/100))
print()
print('Antigo salário: R${}.\n \n >>> Novo salário:   R${}.'.format(salario,round(reajuste,2)))
print()
